version: '3'

services:
  postgres:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    # - "./conf.d:/etc/mysql/conf.d:ro"
